RishavBookReadingEventManagement/ViewModels/AdminHomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RishavBookReadingEventManagement.ViewModels
{
    public class AdminHomeViewModel
    {
        public int ID { get; set; }

        public string BookTitle { get; set; }

     
        public DateTime Date { get; set; }

    
        public string Location { get; set; }

     
        public string StartTime { get; set; }

    }
}

RishavBookReadingEventManagement/ViewModels/CreateNewEventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Shared.CustomDataTypes;

namespace RishavBookReadingEventManagement.ViewModels
{
    public class CreateNewEventViewModel
    {
        [Required]
        public string BookTitle { get; set; }

        [DataType(DataType.Date)]
        [Required]
        public DateTime Date { get; set; }

        [Required]
        public string Location { get; set; }

        [Required]     
        public string StartTime { get; set; }

        [Display(Name = "Event Type")]
        [Required]
        public EventType Type { get; set; }

        [Range(1, 4, ErrorMessage = "Duration must be in 1 to 4 hours")]
        public int? Duration { get; set; }

        [StringLength(50)]
        public string Description { get; set; }

        [StringLength(500)]
        public string OtherDetails { get; set; }

        public string InvitedEmails { get; set; }

    }
}

RishavBookReadingEventManagement/ViewModels/EditBookReadingEventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Shared.CustomDataTypes;

namespace RishavBookReadingEventManagement.ViewModels
{
    public class EditBookReadingEventViewModel
    {
        public int ID { get; set; }
        [Required]
        public string BookTitle { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime Date { get; set; }

        [Required]
        public string Location { get; set; }


        [Required]
        public string StartTime { get; set; }

        [Display(Name = "Event Type")]
        [Required]
        public EventType Type { get; set; }

        [Range(1, 4, ErrorMessage = "Duration must be in 1 to 4 hours")]
        public int? Duration { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        [StringLength(500)]
        public string OtherDetails { get; set; }

        public string InvitedEmails { get; set; }

        public DateTime CreatedOn { get; set; }
        public int UserID { get; set; }
    }
}

RishavBookReadingEventManagement/Controllers/BookReadingEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RishavBookReadingEventManagement.ViewModels;
using BLL;
using Shared.DTO;
using AutoMapper;
using Shared.CustomDataTypes;
using Shared.CustomException;
using Shared.Interfaces;
using DAL.UnitOfWork;

namespace RishavBookReadingEventManagement.Controllers
{
    public class BookReadingEventController : Controller
    {
        IBusinessLayerBookReadingEvent BusinessLayerBookReadingEvent;
        IBusinessLayerPostedComments BusinessLayerPostedComments;
       
        public BookReadingEventController(IBusinessLayerBookReadingEvent businessLayerBookReadingEvent,IBusinessLayerPostedComments businessLayerPostedComments)
        {
          
            BusinessLayerBookReadingEvent = businessLayerBookReadingEvent;           
            BusinessLayerPostedComments = businessLayerPostedComments;

        }
        // GET: BookReadingEvent
       
        public ActionResult Index()
        {
            List<BookReadingEventDTO> eventListDTO = BusinessLayerBookReadingEvent.GetAllEvents();
            HomePageModel homePageModel = new HomePageModel();
            if (Session["userID"] == null)
            {
                foreach (BookReadingEventDTO evt in eventListDTO)
                {
                    if (evt.Type == EventType.Public)
                    {
                        if (evt.Date < DateTime.Now)
                        {
                            homePageModel.PastEvents.Add(evt);
                        }
                        else
                        {
                            homePageModel.FutureEvents.Add(evt);
                        }
                    }
                }
            }
            else
            {
                foreach (BookReadingEventDTO evt in eventListDTO)
                {
                    
                        if (evt.Date < DateTime.Now)
                        {
                            homePageModel.PastEvents.Add(evt);
                        }
                        else
                        {
                            homePageModel.FutureEvents.Add(evt);
                        }
                    
                }
            }

            return View(homePageModel);
        }

        public ActionResult CreateNewEvent()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNewEvent([Bind(Include = "BookTitle, Date, Location,StartTime,Type,Duration,Description,OtherDetails,InvitedEmails")]CreateNewEventViewModel createNewEventViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var config = new MapperConfiguration(cfg => cfg.CreateMap<CreateNewEventViewModel, BookReadingEventDTO>());
                    var mapper = config.CreateMapper();
                    BookReadingEventDTO bookReadingEventDTO = mapper.Map<CreateNewEventViewModel, BookReadingEventDTO>(createNewEventViewModel);
                    bookReadingEventDTO.UserID = int.Parse(Session["userID"].ToString());
                    BusinessLayerBookReadingEvent.CreateNewBookEvent(bookReadingEventDTO);
                    return RedirectToAction("Index");
                }
            }
            catch(FormatException)
            {
                return Content("<h2>Input string is not a sequence of digits.<h2>");
            }
            catch (DataBaseUpdationException exception)
            {
                return Content(exception.Message);
            }
            return View();
        }


        public ActionResult GetBookReadingEventDetails(int id)
        {
            BookReadingEventDTO bookReadingEventDTO = BusinessLayerBookReadingEvent.GetBookReadingEventDetails(id);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<BookReadingEventDTO,BookReadingEventDetailsViewModel>());
            var mapper = config.CreateMapper();
            BookReadingEventDetailsViewModel bookReadingEventDetailsViewModel = mapper.Map<BookReadingEventDTO, BookReadingEventDetailsViewModel>(bookReadingEventDTO);
            return View("GetBookReadingEventDetails", bookReadingEventDetailsViewModel);
        }

        [Authorize]
        public ActionResult GetMyEvents()
        {
            try
            {
                int userID = int.Parse(Session["userID"].ToString());
                List<BookReadingEventDTO> myEventListDTO = BusinessLayerBookReadingEvent.GetMyEvents(userID);
                var config = new MapperConfiguration(cfg => cfg.CreateMap<BookReadingEventDTO, MyBookEventsViewModels>());
                var mapper = config.CreateMapper();
                List<MyBookEventsViewModels> myBookEvents = mapper.Map<List<BookReadingEventDTO>, List<MyBookEventsViewModels>>(myEventListDTO);
                myBookEvents.Reverse();
                return View("GetMyEvents", myBookEvents);
            }
           catch(FormatException)
            {

                return Content("<h1>Input string is not a sequence of digits.<h1>");
            }
            
           
        }

        [Authorize]
        public ActionResult EditBookReadingEvent(int id)
        {
            BookReadingEventDTO bookReadingEventDTO = BusinessLayerBookReadingEvent.GetBookReadingEventDetails(id);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<BookReadingEventDTO, EditBookReadingEventViewModel>());
            var mapper = config.CreateMapper();
            EditBookReadingEventViewModel editBookEvent = mapper.Map<BookReadingEventDTO, EditBookReadingEventViewModel>(bookReadingEventDTO);
            return View(editBookEvent);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBookReadingEvent([Bind(Include = "ID,BookTitle, Date, Location,StartTime,Type,Duration,Description,OtherDetails,InvitedEmails,CreatedOn,UserID")]EditBookReadingEventViewModel editBookReadingEventViewModel)
        {    try
            {
                if (ModelState.IsValid)
                {
                    var config = new MapperConfiguration(cfg => cfg.CreateMap<EditBookReadingEventViewModel, BookReadingEventDTO>());
                    var mapper = config.CreateMapper();
                    BookReadingEventDTO bookReadingEventDTO = mapper.Map<EditBookReadingEventViewModel, BookReadingEventDTO>(editBookReadingEventViewModel);
                    //   bookReadingEventDTO.UserID = int.Parse(Session["userID"].ToString());
                    BusinessLayerBookReadingEvent.EditBookReadingEvent(bookReadingEventDTO);
                    if(Session["emailID"].ToString()=="rishav@admin.com")
                    {
                        return RedirectToAction("AdminHome");
                    }
                    return RedirectToAction("GetMyEvents");

                }
            }
            catch (DataBaseUpdationException exception)
            {
                return Content(exception.Message);
            }
            return View();
        }

        [Authorize]
        public ActionResult GetInvitedEvents()
        {
            string email = Session["emailID"].ToString();
            List<BookReadingEventDTO> list = BusinessLayerBookReadingEvent.InvitedEvents(email);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<BookReadingEventDTO, InvitedEventViewModels>());
            var mapper = config.CreateMapper();
            List<InvitedEventViewModels> invitedEventList= mapper.Map<List<BookReadingEventDTO>, List<InvitedEventViewModels>>(list);

            return View(invitedEventList);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostComment([Bind(Include ="ID,Comments")]BookReadingEventDetailsViewModel bookReadingEventDetailsViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    PostedCommentDTO postedCommentDTO = new PostedCommentDTO();
                    postedCommentDTO.BookReadingEventID = bookReadingEventDetailsViewModel.ID;
                    postedCommentDTO.Comments = bookReadingEventDetailsViewModel.Comments;
                    postedCommentDTO.EmailID = Session["emailID"].ToString();
                    BusinessLayerPostedComments.PostComment(postedCommentDTO);
                    return RedirectToAction("GetBookReadingEventDetails", new { id = bookReadingEventDetailsViewModel.ID });
                }
            }
            catch (DataBaseUpdationException exception)
            {
                return Content(exception.Message);
            }
            return View();
        }

        [ChildActionOnly]
        public ActionResult Comments(int eventID)
        {
            List<PostedCommentDTO> postedCommentDTOs = BusinessLayerPostedComments.GetComments(eventID);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<PostedCommentDTO,PostedCommentViewModel>());
            var mapper = config.CreateMapper();
            List<PostedCommentViewModel> comments= mapper.Map<List<PostedCommentDTO>,List<PostedCommentViewModel>>(postedCommentDTOs);
            return PartialView(comments);

        }

        [Authorize]
        public ActionResult AdminHome()
        {
            List<BookReadingEventDTO> eventListDTO = BusinessLayerBookReadingEvent.GetAllEvents();
            var config = new MapperConfiguration(cfg => cfg.CreateMap<BookReadingEventDTO, AdminHomeViewModel>());
            var mapper = config.CreateMapper();
            List<AdminHomeViewModel> adminHomeViewModels = mapper.Map<List<BookReadingEventDTO>, List<AdminHomeViewModel>>(eventListDTO);
            return View(adminHomeViewModels);
        }
    }
}

RishavBookReadingEventManagement/Views/BookReadingEvent/AdminHome.cshtml
@model IEnumerable<RishavBookReadingEventManagement.ViewModels.AdminHomeViewModel>

@{
    ViewBag.Title = "AdminHome";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>AdminHome</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.BookTitle, "GetBookReadingEventDetails", new { id = item.ID })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditBookReadingEvent", new { id = item.ID })
            |@Html.ActionLink("See Full Details", "GetBookReadingEventDetails", new { id = item.ID })
        </td>
    </tr>
}

</table>

RishavBookReadingEventManagement/Views/BookReadingEvent/Comments.cshtml
@model IEnumerable<RishavBookReadingEventManagement.ViewModels.PostedCommentViewModel>


<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
           Commented By 
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>


        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailID)
        </td>

    </tr>
}

</table>

RishavBookReadingEventManagement/Views/BookReadingEvent/CreateNewEvent.cshtml
@using Shared.CustomDataTypes
@model RishavBookReadingEventManagement.ViewModels.CreateNewEventViewModel

@{
    ViewBag.Title = "CreateNewEvent";
}

<h2>CreateNewEvent</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>CreateNewEventViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.BookTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BookTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BookTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Type,
               new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(Model => Model.StartTime,
                         Enumerable.Range(01, 24).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "-- Hour --")


            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, 5, 10, new { @class = "form-control", @maxlength = "50" })
           
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OtherDetails, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.OtherDetails, 5, 10, new { @class = "form-control" , @maxlength = "500" })
            @Html.ValidationMessageFor(model => model.OtherDetails, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.InvitedEmails, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.InvitedEmails, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.InvitedEmails, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RishavBookReadingEventManagement/Views/BookReadingEvent/EditBookReadingEvent.cshtml
@model RishavBookReadingEventManagement.ViewModels.EditBookReadingEventViewModel

@{
    ViewBag.Title = "EditBookReadingEvent";
}

<h2>EditBookReadingEvent</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>EditBookReadingEventViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(m => m.CreatedOn)
    @Html.HiddenFor(m => m.UserID)
    <div class="form-group">
        @Html.LabelFor(model => model.BookTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BookTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BookTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Type,
               "Select Event Type",
               new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(Model => Model.StartTime,
                         Enumerable.Range(01, 24).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "-- Hour --")


            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, 5, 10, new { @class = "form-control", @maxlength = "50" })

            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OtherDetails, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.OtherDetails, 5, 10, new { @class = "form-control", @maxlength = "500" })
            @Html.ValidationMessageFor(model => model.OtherDetails, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.InvitedEmails, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.InvitedEmails, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.InvitedEmails, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @if (Session["emailID"].ToString() == "rishav@admin.com")
    {
        @Html.ActionLink("Back to List", "AdminHome")
    }
    else
    {
        @Html.ActionLink("Back to List", "Index")

    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RishavBookReadingEventManagement/Views/BookReadingEvent/GetBookReadingEventDetails.cshtml
@model RishavBookReadingEventManagement.ViewModels.BookReadingEventDetailsViewModel

@{
    ViewBag.Title = "Event Details";
}

<h2>GetBookReadingEventDetails</h2>

<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        @if (!string.IsNullOrWhiteSpace(Model.Description))
        {
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        }

        @if (!string.IsNullOrWhiteSpace(Model.OtherDetails))
        {
            <dt>
                @Html.DisplayNameFor(model => model.OtherDetails)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OtherDetails)
            </dd>
        }
        <dt>
            Total Invites :
        </dt>
        @if (!string.IsNullOrWhiteSpace(Model.InvitedEmails))
        {
            <dd>
                @Model.InvitedEmails.Split(',').Count()
            </dd>
        }
        else
        {
            <dd>
                0
            </dd>
        }
        @if (Session["userID"] != null)
        {
            if (Model.Date > DateTime.Now && Model.UserID == int.Parse(Session["userID"].ToString()))
            {
            @Html.ActionLink("Edit", "EditBookReadingEvent", new { id = Model.ID });
            }

        }
    </dl>
</div>
<p>
    @if (Session["emailID"] != null)
    {
        if(Session["emailID"].ToString() == "rishav@admin.com")
        {
                @Html.ActionLink("Back to List", "AdminHome")

        }
        else
        {
                @Html.ActionLink("Back to List", "Index")

        }
    }
</p>

@if (Session["emailID"] != null)
{
using (Html.BeginForm("PostComment", "BookReadingEvent", FormMethod.Post))
{
 @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Enter Comment</h4>
        <hr />
        @Html.HiddenFor(model => model.ID)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comments, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Comments" class="btn btn-default" />
            </div>
        </div>
    </div>
}
}

@{ 
    Html.RenderAction("Comments", new { eventID = Model.ID });
}
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }